import { IWatermark } from './type'

export const DEFAULT_WATERMARK_LIST: IWatermark[] = [
  {
    id: 'bj93tu',
    type: 'text',
    src: 'jisuowei.com',
    text: '',
    position: 'bottom-right',
    scaleType: 'none',
    scalePixel: 200,
    scalePercent: 10,
    offsetType: 'none',
    offsetPixelX: 20,
    offsetPixelY: 20,
    offsetPercentX: 5,
    offsetPercentY: 5,
    repeat: 'none',
    opacity: 1,
    rotate: 0,
    font: '',
    exportSetting: {
      format: 'jpeg',
      quality: .92,
      scaleType: 'none',
      scalePixel: 1080,
      scalePercent: 80,
      saveEXIF: false,
    }
  },
  {
    id: '44m9a8',
    type: 'text',
    src: 'jisuowei.com',
    text: '',
    position: 'bottom-right',
    scaleType: 'none',
    scalePixel: 200,
    scalePercent: 10,
    offsetType: 'none',
    offsetPixelX: 20,
    offsetPixelY: 20,
    offsetPercentX: 5,
    offsetPercentY: 5,
    repeat: 'none',
    opacity: 1,
    rotate: 0,
    font: '',
    exportSetting: {
      format: 'jpeg',
      quality: .92,
      scaleType: 'none',
      scalePixel: 1080,
      scalePercent: 80,
      saveEXIF: false,
    }
  },
]